### ISSUE TITLE
PDF completion

### ISSUE THREAD

**Issue by eugenevr** [resbaz/nectar-cloud-lessons#16]
In the ChecklistCreatingAKeypair.pdf form, I use FoxitPDF,(opens the PDF in browser) and could not copy/paste anything into the "blocks". Small issue but could be annoying to users.

**Comment by MartinPaulo** [comment]
Were you able to type into the blocks?

**Comment by eugenevr** [comment]
Yip.
Afaik copy/paste worked for people who have Adobe Acrobat…

**Comment by MartinPaulo** [comment]
It also works in OSX preview. So at the moment I'm not going to do anything about it. However, I've added a note in the course lessons about this issue, with an instruction to future instructors to keep an eye open for it. If it does turn out that there are lots of other FoxitPDF users then somehow we will have to fix it (switch to html forms?) Thank you for reporting this!
