### ISSUE TITLE
Checklist: Creating a Key Pair: mentions a dialogue should appear, not on Chrome

### ISSUE THREAD

**Issue by bjpop** [resbaz/nectar-cloud-lessons#17]
The Checklist: Creating a Key Pair document mentions:

"A dialogue should appear asking either if you want to open or save a file onto your computer. Choose to save the file to your computer."

Chrome version 46.0.2490.71 on OS X does not open a dialogue, it immediately downloads the file.

**Comment by MartinPaulo** [comment]
Modified in both the course and the workshop to be have a more generic catch all for both types of browser behavior.
