### ISSUE TITLE
Confusing step in "Checklist: Creating a Key Pair"

### ISSUE THREAD

**Issue by gmurtazaa** [resbaz/nectar-cloud-lessons#18]
Hi,

I feel that the second step in the checklist is not really necessary. It has added to the confusion. If the goal is to just create a key pair and when researchers go to "access and security" in the dashboard, they would have the trial project selected by default anyway.

Regards,
Ghulam

**Comment by MartinPaulo** [comment]
In the course proper we aim to teach people to get into the habit of looking at the project drop down before they undertake any major changes - to prevent them from deleting or creating infrastructure in the wrong project. We are trying to reinforce that behavior by putting it into the checklists. But agreed: the way it is done is confusing. We have (hopefully) improved the references in the checklists. Thanks for the suggested improvement!
