### ISSUE TITLE
Checklist: Creating a Security Group: should say why we are doing it before rather than after

### ISSUE THREAD

**Issue by bjpop** [resbaz/nectar-cloud-lessons#20]
The "Checklist: Creating a Security Group" says:

"Congratulations! You have just created a set of rules belonging to a security group that when in place will allow your users to access your web server on port 80 (HTTP) and you as admin on port 22 (SSH)"

however it would be better if this was said before we undertook the actions, rather than after.

Otherwise it comes across as "do a bunch of magical things".

**Comment by MartinPaulo** [comment]
In the course proper we do a short introduction to security groups before we set them off on this checklist. Then afterwards we give a more detailed description. But your point is a good one. I've changed the title of the checklist in both the course and the workshop to reflect the full nature of the task.

Thank you.
