### ISSUE TITLE
Should there be more explanation of what's happening in each steps? Rationale etc?

### ISSUE THREAD

**Issue by nuwang** [resbaz/nectar-cloud-lessons#21]
Some of the steps can be completed mechanically, but without gaining any insight into why it's being done/what's happening. "E.g. In the CIDR edit box ensure that the default of 0.0.0.0/0 is present". What is a CIDR, and what is the significance of 0.0.0.0/0 may not be clear. Just wondering whether this would be something that's explained separately and should not be a part of the checklist, or whether the checklist is meant to provide that too?

**Comment by MartinPaulo** [comment]
We are trying to get people to get something up as soon as is possible. So in the course proper we ask early finishers to try and find it on the internet and then to explain it to the rest of us. But if they don't get there we just describe it as a way of specifying ranges of internet addresses without going into the details. Your typical researcher won't run into it to often, and we don't want to scare them too much :)
