### ISSUE TITLE
navigation instruction in lesson checklists

### ISSUE THREAD

**Issue by JustBerkhout** [resbaz/nectar-cloud-lessons#22]
A minor point of confusion that can come up while following (some of) the checklists (e.g. ChecklistStartingAnInstance.pdf, ChecklistCreatingASecurityGroup.pdf) is this:

-- the first instruction is to navigate to a deep page in the dashboard (e.g. https://dashboard.rc.nectar.org.au/project/access_and_security/) 
-- I navigated to the dashboard home (i.e https://dashboard.rc.nectar.org.au/)
-- this meant that instruction 3 (e.g. The “Key Pairs” tab is selected) was not straightforward, because the KeyPairs tab was still hidden for me.

My suggestion would be to make instruction 1 go to the dashboard home, and instruction 3 includes a click-path to the relevant dashboard tab.

**Comment by MartinPaulo** [comment]
Ok: I've modified the documents in the course to follow this suggested navigation path. Thanks for the suggestion!
