### ISSUE TITLE
ssh command in "Checklist: Launching your Drupal Instance in the Cloud"

### ISSUE THREAD

**Issue by gmurtazaa** [resbaz/nectar-cloud-lessons#24]
Hi,

In checklist "Checklist: Launching your Drupal Instance in the Cloud", the ssh command is given as:

ssh -k key ubuntu@144.6.255.198

It instead should be:

ssh -i key ubuntu@144.6.255.198

Regards,
Ghulam

**Comment by MartinPaulo** [comment]
Now fixed on the workshop code base. Thank you!
