### ISSUE TITLE
Instructions on how to convert pem -> ppk in checklist

### ISSUE THREAD

**Issue by eugenevr** [resbaz/nectar-cloud-lessons#25]
As per https://github.com/davidheijkamp/docs/wiki/Howto:-Creating-and-using-OpenStack---SSH-keypairs-on-Windows

**Comment by MartinPaulo** [comment]
Windows is a problem: we have decided to standardize on MobaXterm (http://mobaxterm.mobatek.net/download-home-edition.html) for the course. But I have added a links page for useful additional information, and added this to it for those that want to use Putty. Thank you!
