### ISSUE TITLE
Clearer Description of Command Line Material in the Slides

### ISSUE THREAD

**Issue by collinstorlie** [resbaz/nectar-cloud-lessons#26]
When command line code appears on a slide there should be a description of all the arguments/commands below it.

For instance, when you show the code - 

$ scp USER_NAME@remotehost notes.txt: .

You could annotate it to something like
'command' 'remote server' 'local file' 'local path'

**Comment by MartinPaulo** [comment]
Rather than try and fill the slides with a extra details, we have added a command line cheat sheet at https://github.com/resbaz/nectar-cloud-lessons/blob/master/Resources/CommandLineCheatSheet.md  There is also a url to point it out to the learners in lesson 3.
