### ISSUE TITLE
Add full or relative path

### ISSUE THREAD

**Issue by weaverbel** [resbaz/nectar-cloud-lessons#27]
Re this in lesson IV:

``` $ scp USER_NAME@remote_machine_address:notes.txt . ```

I would suggest replacing the ```.``` with a path and/or filename. THEN show them a quicker way by showing the ```.``` shortcut.

**Comment by MartinPaulo** [comment]
I have made this change. I will do a full and proper testing with a walk through of the lesson once I've made the other changes suggested for it.

**Comment by MartinPaulo** [comment]
Now walked through this and made sure it works on both Windows and OSX
