### ISSUE TITLE
Lesson I - need to rephrase question about terminating

### ISSUE THREAD

**Issue by weaverbel** [resbaz/nectar-cloud-lessons#28]
Please insert the word 'virtual' in front of 'hard drive' in the question about what happens when you terminate? Confusing otherwise.

**Comment by hoylen** [comment]
Also people might be wondering **which** virtual hard drive: boot disk, ephemeral disk, volume storage, etc.

Must also emphasise "terminate" means a very specific operation. Emphasise that "terminate" is not the same as shutdown, turn off, and other synonyms or other operations.

**Comment by MartinPaulo** [comment]
I've rephrased the question to a simpler: "What happens to your Virtual Machine's hard drive when you **terminate** it?"

**Comment by MartinPaulo** [comment]
I really like the 'boot disk' suggestion: I've changed this portion of the lesson plans to properly reference 'boot disk' rather than 'hard drive'. And of course, the associated question.

**Comment by MartinPaulo** [comment]
I've just checked to confirm: shortly after this question we do go into a section where we emphasise that "terminate" is not the same as shutdown, turn off, etc: and we do cover the differences between the other operations.
