### ISSUE TITLE
Training alpha lessons 3-5

### ISSUE THREAD

**Issue by DFFlanders** [resbaz/nectar-cloud-lessons#4]
add NeCTAR and UniMelb logos alongside V3 logos?

**Comment by DFFlanders** [comment]
explain the command line abbreviated commands a la 'apt' etc. ?

**Comment by DFFlanders** [comment]
very nice metaphor of "mainframe and terminal"

**Comment by DFFlanders** [comment]
maybe a little printed quick reference guide for the command line abbrevations, i.e. man = manual, ls = list, etc.

**Comment by DFFlanders** [comment]
do we need to explain what "bash" is as a programming language?

**Comment by DFFlanders** [comment]
vocab quick ref = ssh (nice metaphor re "teleporting" "Terminal"

**Comment by DFFlanders** [comment]
envelope tear in half with message is a great example.

**Comment by DFFlanders** [comment]
the transition and learning around writing your first SSH command is a bit confusing still, might need to be slowed down and made more of a metaphor?

**Comment by DFFlanders** [comment]
Bug report for Tim to discuss with Martin re SSH'ing from Shell Terminal in resbaz.cloud.edu.au:

~ $ chmod u=rw,go-rwx ~/clay-tablet-flanders.pem ubuntu@130.56.248.76                                                                  
chmod: cannot access 'ubuntu@130.56.248.76': No such file or directory                                                                 
~ $ ls                                                                                                                                 
clay-tablet-flanders.pem                                                                                                               
~ $ ssh -i ~/clay-tablet-flanders.pem ubuntu@130.56.248.76

**Comment by DFFlanders** [comment]
question no.2 slide re O/S perhaps don't talk about knowing image O/S until you have understood the SSH "theatrics"?

**Comment by DFFlanders** [comment]
inner sanctum of being in the operating system (ubuntu) bedroom? giving access to the keys to your bedroom so you are not allowing all your flatmates to let anyone stay the night in your bed!

**Comment by DFFlanders** [comment]
quick ref guide vocab re super user etc apt get etc.

**Comment by DFFlanders** [comment]
ssh is the master key to all bedroom, http is the key to the house.

**Comment by DFFlanders** [comment]
Could we lose Example 12 and leave it to the helpdesk to deal with when they encounter the error?

**Comment by DFFlanders** [comment]
"man in the middle attack" is really important lesson to teach so they can recognise so they can go and call support for help.

**Comment by DFFlanders** [comment]
dialogue re excercise 12: 
You: "hi support I think I am experieing a man in the middle attack - or maybe my IP has been changed?  I'm not sure, can you help me please"
SupportDesk: "yes of course, this will take about 5 minutes to do but I'll walk you through it"

**Comment by DFFlanders** [comment]
Summary of lesson 3 (after the tea break from lesson 1&2):
a..) 15 minute theatrical play on Brunswick house, Martin directs play and shows how each command instructs the thesbians.
b.) 10min tick list of bash commands they will use to trial these things themselves.
c.) 5 min on recognising a "man in the middle attack" OR "IP Change". <-- could be a last little one act ;-)

**Comment by MartinPaulo** [comment]
I've now worked through all of these, and implemented them...
