### ISSUE TITLE
Lesson 3 is missing

### ISSUE THREAD

**Issue by hooliowobbits** [resbaz/nectar-cloud-lessons#42]
and has been split into 3 separate files.

suggest renaming them to 
lesson_3a_AccessingYourComputer.html
lesson_3b_CommandLineIntro.html 
etc.

also, generally, each of the lessons ought have their subject in their filename eg; 
lesson_1_RollUpToTheResearchCloud.html etc

**Comment by MartinPaulo** [comment]
Now dealt with by your handy naming scheme!
