### ISSUE TITLE
X2Go

### ISSUE THREAD

**Issue by MartinPaulo** [resbaz/nectar-cloud-lessons#44]
Consider adding X2Go into the Xwindows lessons
http://wiki.x2go.org/doku.php
https://www.howtoforge.com/how-to-install-x2goserver-on-ubuntu-14.04-as-vnc-alternative

**Comment by JustBerkhout** [comment]
As a basis for the X2Go lesson, we're aiming to cover this TPAC public Nectar image, with instructions here: https://support.nectar.org.au/support/solutions/articles/6000090909-tpac-remote-desktop-user-guide

**Comment by hooliowobbits** [comment]
I'll create a cloud lesson for this.  We already have some user doco written at https://support.nectar.org.au/support/solutions/articles/6000090909-tpac-remote-desktop-user-guide which i'll roughly follow.  as per the conversation with martin on slack, i'll write a new lesson (as opposed to morphing the existing x forwarding one)

**Comment by MartinPaulo** [comment]
Nicely done: thank you!
