### ISSUE TITLE
Alpha training lessons 4 & 5

### ISSUE THREAD

**Issue by DFFlanders** [resbaz/nectar-cloud-lessons#5]
feedback on lessons from session at 9am on Sept 3rd...

**Comment by DFFlanders** [comment]
add scp to quick ref guide of commands for bash

**Comment by DFFlanders** [comment]
for example code maybe provide both generic commands like USER-NAME but also then do an e.g. with the name of our persona AnnaFoobar@MachineID

**Comment by DFFlanders** [comment]
core learning objective of lesson 4 is moving data to and from your new machine.... so you can make it available to whatever "cloud app"y you build like your drupal website which is showcasing your research... or perhaps you use the RStudio app to do data analysis on it, etc.  In short you want your data on your server in the cloud so you can use multiple research apps with it.

**Comment by DFFlanders** [comment]
cloud = someone else's computer.

**Comment by DFFlanders** [comment]
each time a previous bash command is used, point to people randomly to ask them what the command means.

**Comment by DFFlanders** [comment]
add rm to list of frequently used commands. nice metaphor re kryptonite.

**Comment by DFFlanders** [comment]
would be great to provide analogies for each of the bash commands in the frequently used commands?

**Comment by DFFlanders** [comment]
ask for participants to tell you what to type at each space and slash in the bash script.

**Comment by DFFlanders** [comment]
scp is like teleporting!

**Comment by DFFlanders** [comment]
three cup game, three card monty, etc. as example of moving data files around on your local and remote server

**Comment by DFFlanders** [comment]
a bulk scp command for uploading files to a remote file store via command line?

**Comment by DFFlanders** [comment]
Moving onto lesson 5 at 9:48

**Comment by DFFlanders** [comment]
quick quiz, first answers wins... who can get through their friend "man" the quickest to find out what -Y is doing?

**Comment by DFFlanders** [comment]
apt is like app on the app store <-- for the quick reference guide on bash commands

**Comment by DFFlanders** [comment]
DFF talk to Tim to ask about X11 software and remotely running NoVNC with firefox to work on the cloud?

**Comment by DFFlanders** [comment]
end of lesson for X11 session.

**Comment by MartinPaulo** [comment]
All of these are now in the course, one way or the other.
