### ISSUE TITLE
Lesson 6: snapshots, backup, etc.

### ISSUE THREAD

**Issue by DFFlanders** [resbaz/nectar-cloud-lessons#6]
quizes around what the different snapshot commands mean, while snapshot command is running: pause instance, suspend instance, soft reboot, hard reboot, shut off, rebuild, terminate.

**Comment by DFFlanders** [comment]
scenarios for what you'll need to know when colleagues have found out about your new cloud manager skills, and want you to do different things with their images: one colleague wants things backed up and archived for long term, one one a clean install, one wants.... foobar

**Comment by DFFlanders** [comment]
nice question no.2 where you can have people explain their choices and explain why.

**Comment by DFFlanders** [comment]
do we need a ticklist for the steps around creating a snapshot as well as other shutoff/reboots/terminate/etc.

**Comment by DFFlanders** [comment]
have object storage and transient storage together (next to each other)? <-- if possible and simplify

**Comment by MartinPaulo** [comment]
I've handled all of these bar the scenario's: which I've added to the read me as a suggested improvement.
